hockeyblog/hockeyblog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^search/', include(('search.urls', 'search'), namespace='search')),
    path("", include("post.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hockeyblog/post/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path("", views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail')
]

hockeyblog/search/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import searchposts


urlpatterns = [
    url(r"^$", searchposts, name="searchposts"),
]

hockeyblog/post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

STATUS = ((0, "Draft"), (1, "Publish"))


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=200)
    image = models.ImageField(upload_to="images")
    cups = models.CharField(max_length=200)
    team_name = models.CharField(max_length=200)
    status = models.IntegerField(choices=STATUS, default=0)
    
    def __str__(self):
        return self.title

    class Meta:
        ordering = ["created_on"]

hockeyblog/search/models.py
from django.db import models

# Create your models here.

hockeyblog/post/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views import generic
from .models import Post

# Create your views here.


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("created_on")
    template_name = "index.html"
    context_object_name = "posts"
class PostDetail(generic.DetailView):
    model = Post
    template_name = "post_detail.html"

hockeyblog/search/views.py
from django.shortcuts import render
from django.db.models import Q
from post.models import Post


def searchposts(request):
    if request.method == "GET":
        query = request.GET.get("q")

        submitbutton = request.GET.get("submit")

        if query is not None:
            lookups = Q(title__icontains=query) | Q(content__icontains=query)

            results = Post.objects.filter(lookups).distinct()

            context = {"results": results, "submitbutton": submitbutton}

            return render(request, "search/search.html", context)
            
        else:
            return render(request, "search/search.html")
           
    else:
        return render(request, "search/search.html")
        

hockeyblog/post/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous"> 
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    
    <title>{%block title%}Hockey life{%endblock%}</title>
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-danger">
        <a class="navbar-brand" href="/">
        Hockey Life
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>  
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link"href="/">Teams</a>
              </li>
              <li class="nav-item">
                <a class="nav-link"href="/">Cups</a>
              </li>
              <form action="{% url 'search:searchposts' %}" method="get">
              <input type="q" placeholder="Search.."><button id='Submit'>Submit</button>
              </form>
            </ul>
        </div>
    </nav>
 
    
     {% block content %}



     {% endblock %}

     {% block footer%}
     <footer class="py-3 bg-grey">
      <!-- footer items-->
      <p class="m-0 text-dark text-center ">Copyright &copy; <a href="http://MatthewSmithWebDesign.com">Matthew Smith</p></a>
  </footer>
     {% endblock%}

<script src="<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
 
</body>


</html>

hockeyblog/post/templates/index.html
{% extends "base.html" %} 
{% load static %}
{% static 'css/main.css' %}

{% block content %}


<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Hockey Life</h3>
                    <p class="text-light">A blog wherewe talk all things hockey.
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Post Columns -->
        <div class="col-md-8 mt-3 left">
            {% for post in posts %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|truncatewords:15 }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{%endblock%}

hockeyblog/post/templates/post_detail.html
{% extends 'base.html' %} 
{% load static %}
{% static 'css/main.css' %}
{% block content %}
{% load thumbnail %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ object.author }}  {{ object.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }} <img src="{{ object.image.url }}"></p>
      </div>
    </div>
</div>

{% endblock content %}

hockeyblog/post/templates/search.html
<h1>Search Page</h1>

<br/>
<form action="{% url 'search:searchposts' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for result in results %}

{{result.title}}
<br/>

{{result.content}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

hockeyblog/post/templates/search/search.html
{% extends "base.html" %} 

<h1>Search Page</h1>
{% block content%}
<br/>
<form action="{% url 'search:searchposts' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="searchposts"/>
<input type="submit" name="submit" value="Search"/>
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for result in results %}

{{result.title}}
<br/>

{{result.content}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}
{% endblock %}